"""index user data and require expense owner

Revision ID: b60426c36da2
Revises: 88082bcca661
Create Date: 2026-09-30 17:23:21.260311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60426c36da2'
down_revision: Union[str, Sequence[str], None] = '88082bcca661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    connection = op.get_bind()
    gastos_sin_usuario = connection.execute(
        sa.text("SELECT COUNT(*) FROM gastos WHERE usuario_id IS NULL")
    ).scalar() or 0
    if gastos_sin_usuario:
        raise RuntimeError(
            f"No se puede exigir propietario: hay {gastos_sin_usuario} gastos sin usuario_id"
        )
    referencias_inversiones = connection.execute(
        sa.text(
            "SELECT COUNT(*) FROM inversiones "
            "WHERE gasto_fijo_id IS NOT NULL OR ingreso_fijo_id IS NOT NULL"
        )
    ).scalar() or 0
    if referencias_inversiones:
        raise RuntimeError(
            "No se pueden retirar columnas heredadas: hay inversiones con referencias a movimientos fijos"
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_tokens_purpose'))
        batch_op.drop_index(batch_op.f('ix_account_tokens_usuario_id'))
        batch_op.create_index('ix_account_tokens_user_purpose_created', ['usuario_id', 'purpose', 'created_at'], unique=False)

    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index('ix_gastos_usuario_fecha', ['usuario_id', 'fecha'], unique=False)

    with op.batch_alter_table('gastos_fijos', schema=None) as batch_op:
        batch_op.create_index('ix_gastos_fijos_usuario_activo_dia', ['usuario_id', 'activo', 'dia_mes'], unique=False)

    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.create_index('ix_ingresos_usuario_fecha', ['usuario_id', 'fecha'], unique=False)

    with op.batch_alter_table('ingresos_fijos', schema=None) as batch_op:
        batch_op.create_index('ix_ingresos_fijos_usuario_activo_dia', ['usuario_id', 'activo', 'dia_mes'], unique=False)

    with op.batch_alter_table('inversiones', schema=None) as batch_op:
        batch_op.drop_column('gasto_fijo_id')
        batch_op.drop_column('ingreso_fijo_id')
        batch_op.create_index('ix_inversiones_usuario_fecha', ['usuario_id', 'fecha'], unique=False)

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_attempted_at'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_rate_key'))
        batch_op.create_index('ix_login_attempts_rate_time', ['rate_key', 'attempted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_login_attempts_rate_time')
        batch_op.create_index(batch_op.f('ix_login_attempts_rate_key'), ['rate_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_attempted_at'), ['attempted_at'], unique=False)

    with op.batch_alter_table('inversiones', schema=None) as batch_op:
        batch_op.drop_index('ix_inversiones_usuario_fecha')
        batch_op.add_column(sa.Column('ingreso_fijo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gasto_fijo_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('ingresos_fijos', schema=None) as batch_op:
        batch_op.drop_index('ix_ingresos_fijos_usuario_activo_dia')

    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.drop_index('ix_ingresos_usuario_fecha')

    with op.batch_alter_table('gastos_fijos', schema=None) as batch_op:
        batch_op.drop_index('ix_gastos_fijos_usuario_activo_dia')

    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.drop_index('ix_gastos_usuario_fecha')
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('account_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_account_tokens_user_purpose_created')
        batch_op.create_index(batch_op.f('ix_account_tokens_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_tokens_purpose'), ['purpose'], unique=False)

    # ### end Alembic commands ###
