"""add recurring movement foreign keys

Revision ID: 291678c335f0
Revises: b60426c36da2
Create Date: 2026-09-30 17:41:09.543427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291678c335f0'
down_revision: Union[str, Sequence[str], None] = 'b60426c36da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    connection = op.get_bind()
    gastos_huerfanos = connection.execute(
        sa.text(
            "SELECT COUNT(*) FROM gastos g "
            "LEFT JOIN gastos_fijos f ON f.id = g.gasto_fijo_id "
            "WHERE g.gasto_fijo_id IS NOT NULL AND f.id IS NULL"
        )
    ).scalar() or 0
    ingresos_huerfanos = connection.execute(
        sa.text(
            "SELECT COUNT(*) FROM ingresos i "
            "LEFT JOIN ingresos_fijos f ON f.id = i.ingreso_fijo_id "
            "WHERE i.ingreso_fijo_id IS NOT NULL AND f.id IS NULL"
        )
    ).scalar() or 0
    if gastos_huerfanos or ingresos_huerfanos:
        raise RuntimeError("No se pueden agregar claves foráneas: hay referencias a movimientos fijos inexistentes")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_gastos_gasto_fijo_id_gastos_fijos',
            'gastos_fijos',
            ['gasto_fijo_id'],
            ['id'],
        )

    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_ingresos_ingreso_fijo_id_ingresos_fijos',
            'ingresos_fijos',
            ['ingreso_fijo_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ingresos_ingreso_fijo_id_ingresos_fijos', type_='foreignkey')

    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_gastos_gasto_fijo_id_gastos_fijos', type_='foreignkey')

    # ### end Alembic commands ###
